# Generated by Django 5.2.15 on 2026-06-15 03:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_companymember_can_generate_documents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('username_synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('awaiting_new_session_verification', 'Awaiting new session verification'), ('revoked', 'Revoked'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('initialization_context', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('relink_requested_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_identity', to='teams.companymember')),
            ],
            options={
                'db_table': 'telegram_identities',
            },
        ),
        migrations.CreateModel(
            name='TelegramLinkChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_challenges', to='teams.companymember')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_link_challenges_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_link_challenges',
            },
        ),
        migrations.CreateModel(
            name='TelegramMiniAppSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('init_data_hash', models.CharField(max_length=128, unique=True)),
                ('auth_date', models.DateTimeField()),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(blank=True, default='', max_length=255)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_app_sessions', to='telegram.telegramidentity')),
            ],
            options={
                'db_table': 'telegram_mini_app_sessions',
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('matching_lot', 'Matching lot'), ('deadline_reminder', 'Deadline reminder'), ('analysis_status', 'Analysis status'), ('document_status', 'Document status'), ('security', 'Security')], max_length=40)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('push', 'Push')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('payload_metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='teams.companymember')),
            ],
            options={
                'db_table': 'notification_deliveries',
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_7ba7c6_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_key', 'member', 'channel'), name='unique_notification_delivery')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('matching_lot', 'Matching lot'), ('deadline_reminder', 'Deadline reminder'), ('analysis_status', 'Analysis status'), ('document_status', 'Document status'), ('security', 'Security')], max_length=40)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('push', 'Push')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('threshold', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quiet_hours', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='teams.companymember')),
            ],
            options={
                'db_table': 'notification_preferences',
                'constraints': [models.UniqueConstraint(fields=('member', 'event_type', 'channel'), name='unique_member_event_channel_preference'), models.CheckConstraint(condition=models.Q(('threshold__isnull', True), ('threshold__lte', 100), _connector='OR'), name='notification_threshold_lte_100')],
            },
        ),
        migrations.AddIndex(
            model_name='telegramidentity',
            index=models.Index(fields=['member', 'status'], name='telegram_id_member__82077b_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramidentity',
            index=models.Index(fields=['username'], name='telegram_id_usernam_1ff283_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramidentity',
            index=models.Index(fields=['chat_id'], name='telegram_id_chat_id_f20fd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='telegramidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'verified'), ('telegram_user_id__isnull', False)), fields=('telegram_user_id',), name='unique_verified_telegram_user_id'),
        ),
        migrations.AddIndex(
            model_name='telegramlinkchallenge',
            index=models.Index(fields=['member', 'expires_at', 'consumed_at'], name='telegram_li_member__9cb842_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramminiappsession',
            index=models.Index(fields=['identity', 'revoked_at', 'last_active_at'], name='telegram_mi_identit_5891e3_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramminiappsession',
            index=models.Index(fields=['expires_at'], name='telegram_mi_expires_eca8b6_idx'),
        ),
    ]
