# Generated by Django 5.2.14 on 2026-05-22 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITenderAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing_docs', 'Hujjatlar qayta ishlanmoqda'), ('checking_compliance', 'Talablar tekshirilmoqda'), ('detecting_red_flags', 'Risklar aniqlanmoqda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=40)),
                ('eligibility_score', models.PositiveSmallIntegerField(default=0)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('missing_documents', models.JSONField(blank=True, default=list)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('standards', models.JSONField(blank=True, default=list)),
                ('decision', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='companies.companyprofile')),
                ('tender_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='tenders.tenderlot')),
            ],
            options={
                'db_table': 'ai_tender_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartCalculator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('logistics_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('calculated_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('calculated_operator_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('calculated_zakalat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('min_safe_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('recommended_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculator', to='analysis.aitenderanalysis')),
            ],
            options={
                'db_table': 'smart_calculators',
            },
        ),
        migrations.AddIndex(
            model_name='aitenderanalysis',
            index=models.Index(fields=['company', 'analysis_status'], name='ai_tender_a_company_c7780f_idx'),
        ),
        migrations.AddIndex(
            model_name='aitenderanalysis',
            index=models.Index(fields=['tender_lot'], name='ai_tender_a_tender__1fc978_idx'),
        ),
    ]
