# Generated by Django 5.2.15 on 2026-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('companies', '0004_companyprofile_company_stir_format_and_more'),
        ('tenders', '0004_tendersource_tenderlot_external_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aitenderanalysis',
            constraint=models.CheckConstraint(condition=models.Q(('eligibility_score__lte', 100)), name='analysis_eligibility_score_range'),
        ),
        migrations.AddConstraint(
            model_name='smartcalculator',
            constraint=models.CheckConstraint(condition=models.Q(('raw_material_cost__gte', 0), ('logistics_cost__gte', 0), ('labor_cost__gte', 0), ('other_expenses__gte', 0), ('calculated_vat__gte', 0), ('calculated_operator_fee__gte', 0), ('calculated_zakalat__gte', 0), ('min_safe_price__gte', 0), ('recommended_price__gte', 0)), name='calculator_amounts_non_negative'),
        ),
    ]
