# Generated by Django 5.2.15 on 2026-06-16 06:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_aitenderanalysis_analysis_eligibility_score_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('prompt_version', models.CharField(default='analysis-v1', max_length=40)),
                ('additional_text', models.TextField(blank=True, default='')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='run', to='analysis.aitenderanalysis')),
            ],
            options={
                'db_table': 'analysis_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_type', models.CharField(choices=[('risk', 'Risk factor'), ('compliance', 'Compliance'), ('requirement', 'Requirement'), ('document', 'Missing document'), ('standard', 'Standard')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('risk_factor', models.CharField(blank=True, default='', max_length=80)),
                ('rating_score', models.PositiveSmallIntegerField(default=0)),
                ('compliance_status', models.CharField(blank=True, default='', max_length=80)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='analysis.analysisrun')),
            ],
            options={
                'db_table': 'analysis_findings',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelInvocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='google_gemini', max_length=80)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_version', models.CharField(max_length=40)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('calculated_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_invocations', to='analysis.analysisrun')),
            ],
            options={
                'db_table': 'model_invocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['status', 'created_at'], name='analysis_ru_status_50da1f_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['analysis'], name='analysis_ru_analysi_cd93dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__lte', 100)), name='analysis_run_progress_percent_range'),
        ),
        migrations.AddIndex(
            model_name='analysisfinding',
            index=models.Index(fields=['run', 'finding_type'], name='analysis_fi_run_id_d84566_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisfinding',
            constraint=models.CheckConstraint(condition=models.Q(('rating_score__lte', 100)), name='analysis_finding_rating_score_range'),
        ),
        migrations.AddIndex(
            model_name='modelinvocation',
            index=models.Index(fields=['run', 'provider', 'created_at'], name='model_invoc_run_id_fa600b_idx'),
        ),
    ]
