# Generated by Django 5.2.15 on 2026-06-17 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysisrun_analysisfinding_modelinvocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalKnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('authority_level', models.CharField(choices=[('primary_normative', 'Primary normative'), ('official_context', 'Official context'), ('technical_standard', 'Technical standard')], max_length=40)),
                ('base_url', models.URLField()),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('source_rank', models.PositiveSmallIntegerField(default=100)),
                ('requires_effective_date_check', models.BooleanField(default=True)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'legal_knowledge_sources',
                'ordering': ['source_rank', 'code'],
                'indexes': [models.Index(fields=['is_active', 'authority_level', 'source_rank'], name='legal_knowl_is_acti_d282cb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_rank__gte', 1)), name='legal_source_rank_positive')],
            },
        ),
        migrations.CreateModel(
            name='LegalKnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('language', models.CharField(default='uz', max_length=12)),
                ('document_type', models.CharField(blank=True, default='', max_length=80)),
                ('document_number', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('future', 'Future effective'), ('archived', 'Archived')], default='active', max_length=20)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('version_label', models.CharField(blank=True, default='', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='analysis.legalknowledgesource')),
            ],
            options={
                'db_table': 'legal_knowledge_documents',
                'ordering': ['source__source_rank', 'title', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='LegalKnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('section_path', models.CharField(blank=True, default='', max_length=255)),
                ('article_number', models.CharField(blank=True, default='', max_length=40)),
                ('text', models.TextField()),
                ('text_hash', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='analysis.legalknowledgedocument')),
            ],
            options={
                'db_table': 'legal_knowledge_chunks',
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'article_number'], name='legal_knowl_documen_e2705b_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_legal_document_chunk'), models.CheckConstraint(condition=models.Q(('text_hash__gt', '')), name='legal_chunk_hash_not_empty')],
            },
        ),
        migrations.AddIndex(
            model_name='legalknowledgedocument',
            index=models.Index(fields=['source', 'status', 'effective_from'], name='legal_knowl_source__a6d618_idx'),
        ),
        migrations.AddIndex(
            model_name='legalknowledgedocument',
            index=models.Index(fields=['document_type', 'document_number'], name='legal_knowl_documen_7b1508_idx'),
        ),
        migrations.AddConstraint(
            model_name='legalknowledgedocument',
            constraint=models.UniqueConstraint(fields=('source', 'external_id', 'version_label'), name='unique_legal_document_version'),
        ),
        migrations.AddConstraint(
            model_name='legalknowledgedocument',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='legal_document_effective_period_valid'),
        ),
    ]
