# Generated by Django 5.2.15 on 2026-06-14 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_companyprofile_current_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=list)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('price_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['rank', 'code'],
                'indexes': [models.Index(fields=['is_active', 'is_public', 'rank'], name='subscriptio_is_acti_b4104e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('paused', 'Paused'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('source', models.CharField(choices=[('system', 'System'), ('payment', 'Payment provider'), ('admin', 'Admin override')], default='system', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='companies.companyprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'db_table': 'company_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('ai_analysis', 'AI analysis'), ('document_generation', 'Document generation'), ('document_export', 'Document export'), ('competitor_query', 'Competitor query')], max_length=50)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('used', models.PositiveBigIntegerField(default=0)),
                ('limit_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='companies.companyprofile')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='subscriptions.companysubscription')),
            ],
            options={
                'db_table': 'usage_records',
                'ordering': ['-period_start', 'metric'],
            },
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['company', 'status'], name='company_sub_company_0bf828_idx'),
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['status', 'current_period_end'], name='company_sub_status_ca395a_idx'),
        ),
        migrations.AddConstraint(
            model_name='companysubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['trialing', 'active'])), fields=('company',), name='one_live_subscription_per_company'),
        ),
        migrations.AddConstraint(
            model_name='companysubscription',
            constraint=models.CheckConstraint(condition=models.Q(('current_period_end__gt', models.F('current_period_start'))), name='subscription_period_is_valid'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['company', 'metric', 'period_end'], name='usage_recor_company_5b3c99_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.UniqueConstraint(fields=('company', 'metric', 'period_start', 'period_end'), name='unique_company_metric_period'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='usage_period_is_valid'),
        ),
    ]
