# Generated by Django 5.2.15 on 2026-06-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companyprofile_current_tariff'),
        ('subscriptions', '0002_seed_plans_and_legacy_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='scheduled_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='scheduled_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='scheduled_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_company_subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['status', 'scheduled_change_at'], name='company_sub_status_9d61c9_idx'),
        ),
    ]
