# Generated by Django 5.2.15 on 2026-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyprofile_company_stir_format_and_more'),
        ('subscriptions', '0003_companysubscription_scheduled_change_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companysubscription',
            constraint=models.CheckConstraint(condition=models.Q(('trial_ends_at__isnull', True), ('trial_ends_at__gte', models.F('starts_at')), _connector='OR'), name='subscription_trial_period_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='companysubscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scheduled_change_at__isnull', True), ('scheduled_plan__isnull', True)), models.Q(('scheduled_change_at__isnull', False), ('scheduled_plan__isnull', False)), _connector='OR'), name='subscription_schedule_pair_complete'),
        ),
        migrations.AddConstraint(
            model_name='companysubscription',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_period_end__isnull', True), models.Q(('scheduled_change_at__isnull', False), ('scheduled_period_end__gt', models.F('scheduled_change_at')), ('scheduled_plan__isnull', False)), _connector='OR'), name='subscription_scheduled_period_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.CheckConstraint(condition=models.Q(('price_uzs__isnull', True), ('price_uzs__gte', 0), _connector='OR'), name='subscription_plan_price_non_negative'),
        ),
    ]
