# Generated by Django 5.2.15 on 2026-06-16 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


SMS_QUOTA_MATRIX = {
    'free': (0, 0),
    'pro': (100, 5),
    'business': (500, 20),
    'enterprise': (500, 20),
}


def backfill_subscription_sms_quotas(apps, schema_editor):
    CompanySubscription = apps.get_model(
        'subscriptions',
        'CompanySubscription',
    )
    period_start = timezone.localdate().replace(day=1)
    subscriptions = CompanySubscription.objects.select_related('plan')
    for subscription in subscriptions.iterator():
        monthly, daily = SMS_QUOTA_MATRIX.get(subscription.plan.code, (0, 0))
        subscription.sms_allowed_monthly = monthly
        subscription.daily_sms_cap = daily
        subscription.sms_counter_period_start = period_start
        subscription.sms_sent_this_month = min(
            subscription.sms_sent_this_month,
            monthly,
        )
        subscription.save(update_fields=[
            'sms_allowed_monthly',
            'daily_sms_cap',
            'sms_counter_period_start',
            'sms_sent_this_month',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyprofile_company_stir_format_and_more'),
        ('subscriptions', '0005_update_public_plan_prices'),
        ('teams', '0002_companymember_can_generate_documents_and_more'),
        ('tenders', '0006_scraperun_scrapeerror_tenderdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('throttled', 'Throttled'), ('failed', 'Failed')], max_length=20)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='daily_sms_cap',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='sms_allowed_monthly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='sms_counter_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='sms_sent_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            backfill_subscription_sms_quotas,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='companysubscription',
            constraint=models.CheckConstraint(condition=models.Q(('sms_sent_this_month__lte', models.F('sms_allowed_monthly'))), name='subscription_sms_monthly_counter_within_cap'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='teams.companymember'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='tenders.tenderdocument'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'sent_at'], name='notificatio_user_id_97b8a9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['team', 'sent_at'], name='notificatio_team_id_41752a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['tender', 'status'], name='notificatio_tender__468311_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'sent_at'], name='notificatio_status_be9b86_idx'),
        ),
    ]
