# Generated by Django 5.2.15 on 2026-06-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_notificationlog_companysubscription_daily_sms_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('throttled', 'Throttled'), ('failed', 'Failed')], max_length=20),
        ),
    ]
