# Generated by Django 5.2.15 on 2026-06-16 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyprofile_company_stir_format_and_more'),
        ('subscriptions', '0007_alter_notificationlog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('click', 'CLICK'), ('payme', 'Payme'), ('uzum', 'Uzum')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('prepared', 'Prepared'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('merchant_trans_id', models.CharField(max_length=64, unique=True)),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='companies.companyprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='subscriptions.subscriptionplan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='subscriptions.companysubscription')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('click', 'CLICK'), ('payme', 'Payme'), ('uzum', 'Uzum')], max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('provider_event_id', models.CharField(max_length=128)),
                ('action', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='subscriptions.paymenttransaction')),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['company', 'status', 'created_at'], name='payment_tra_company_f7d911_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='payment_tra_provide_d19edc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'provider_transaction_id'], name='payment_tra_provide_0544ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_transaction_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['provider', 'event_type', 'received_at'], name='webhook_eve_provide_f8cbf9_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status', 'received_at'], name='webhook_eve_status_f769dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_event_id', 'action'), name='unique_provider_webhook_action'),
        ),
    ]
