# Generated by Django 5.2.14 on 2026-05-22 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenderLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(max_length=100, unique=True)),
                ('platform_source', models.CharField(choices=[('xarid_uzex', 'xarid.uzex.uz'), ('dxarid_uzex', 'dxarid.uzex.uz'), ('exarid_uzex', 'exarid.uzex.uz'), ('e_auksion', 'e-auksion.uz'), ('manual', "Qo'lda kiritilgan")], default='manual', max_length=30)),
                ('title', models.TextField()),
                ('buyer_name', models.CharField(blank=True, default='', max_length=500)),
                ('start_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('zakalat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('posted_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=50)),
                ('raw_portal_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tender_lots',
                'ordering': ['-posted_date'],
                'indexes': [models.Index(fields=['status', 'deadline'], name='tender_lots_status_5c0353_idx'), models.Index(fields=['platform_source'], name='tender_lots_platfor_3f28ad_idx'), models.Index(fields=['region'], name='tender_lots_region_170ac0_idx'), models.Index(fields=['category'], name='tender_lots_categor_ff4ed7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenderDocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('raw_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tenders.tenderlot')),
            ],
            options={
                'db_table': 'tender_document_chunks',
                'ordering': ['tender_lot_id', 'chunk_index'],
                'unique_together': {('tender_lot', 'file_name', 'chunk_index')},
            },
        ),
    ]
