# Generated by Django 5.2.15 on 2026-06-14 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


SOURCE_ROWS = {
    'xarid_uzex': {
        'name': 'xarid.uzex.uz',
        'base_url': 'https://xarid.uzex.uz',
    },
    'dxarid_uzex': {
        'name': 'dxarid.uzex.uz',
        'base_url': 'https://dxarid.uzex.uz',
    },
    'exarid_uzex': {
        'name': 'exarid.uzex.uz',
        'base_url': 'https://exarid.uzex.uz',
    },
    'e_auksion': {
        'name': 'e-auksion.uz',
        'base_url': 'https://e-auksion.uz',
    },
    'manual': {
        'name': 'Manual input',
        'base_url': '',
    },
}


def seed_sources_and_backfill_lots(apps, schema_editor):
    TenderSource = apps.get_model('tenders', 'TenderSource')
    TenderLot = apps.get_model('tenders', 'TenderLot')

    sources = {}
    for code, defaults in SOURCE_ROWS.items():
        source, _ = TenderSource.objects.get_or_create(
            code=code,
            defaults=defaults,
        )
        sources[code] = source

    for code, source in sources.items():
        lots = TenderLot.objects.filter(platform_source=code)
        lots.update(source=source)
        if code != 'manual':
            lots.update(external_id=models.F('lot_number'))


def clear_source_backfill(apps, schema_editor):
    TenderSource = apps.get_model('tenders', 'TenderSource')
    TenderLot = apps.get_model('tenders', 'TenderLot')

    TenderLot.objects.update(source=None, external_id='')
    TenderSource.objects.filter(code__in=SOURCE_ROWS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_postgresql_trigram_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tender_sources',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='tenderlot',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tenderlot',
            name='raw_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tenderlot',
            name='lot_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='tenderlot',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='tenders.tendersource'),
        ),
        migrations.RunPython(
            seed_sources_and_backfill_lots,
            clear_source_backfill,
        ),
        migrations.AddIndex(
            model_name='tenderlot',
            index=models.Index(fields=['source', 'status', 'deadline'], name='tender_lots_source__b0dc5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenderlot',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False), models.Q(('external_id', ''), _negated=True)), fields=('source', 'external_id'), name='unique_tender_source_external_id'),
        ),
        migrations.AddConstraint(
            model_name='tenderlot',
            constraint=models.CheckConstraint(condition=models.Q(('start_price__gte', 0)), name='tender_start_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tenderlot',
            constraint=models.CheckConstraint(condition=models.Q(('zakalat_amount__gte', 0)), name='tender_zakalat_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tenderlot',
            constraint=models.CheckConstraint(condition=models.Q(('deadline__gt', models.F('posted_date'))), name='tender_deadline_after_posted'),
        ),
        migrations.AddConstraint(
            model_name='tenderlot',
            constraint=models.CheckConstraint(condition=models.Q(('external_id', ''), ('source__isnull', False), _connector='OR'), name='tender_external_id_requires_source'),
        ),
    ]
