# Generated by Django 5.2.15 on 2026-06-16 06:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_enforce_tender_source_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrape_runs', to='tenders.tendersource')),
            ],
            options={
                'db_table': 'scrape_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(blank=True, default='')),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrape_errors', to='tenders.tendersource')),
                ('scrape_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='tenders.scraperun')),
            ],
            options={
                'db_table': 'scrape_errors',
                'ordering': ['-failed_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tender_id', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('organization_name', models.CharField(blank=True, default='', max_length=500)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('published_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('hash_sum', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scrape_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tenders.scraperun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='tenders.tendersource')),
                ('tender_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='tenders.tenderlot')),
            ],
            options={
                'db_table': 'tender_documents',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scraperun',
            index=models.Index(fields=['source', 'status', 'started_at'], name='scrape_runs_source__46bc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapeerror',
            index=models.Index(fields=['source', 'failed_at'], name='scrape_erro_source__e84375_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderdocument',
            index=models.Index(fields=['source', 'tender_id'], name='tender_docu_source__f6a4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderdocument',
            index=models.Index(fields=['source', 'deadline_at'], name='tender_docu_source__a9e8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderdocument',
            index=models.Index(fields=['hash_sum'], name='tender_docu_hash_su_7d7050_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenderdocument',
            constraint=models.UniqueConstraint(fields=('source', 'tender_id'), name='unique_tender_document_source_tender_id'),
        ),
        migrations.AddConstraint(
            model_name='tenderdocument',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='tender_document_total_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tenderdocument',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at__gt', models.F('published_at'))), name='tender_document_deadline_after_published'),
        ),
    ]
