export const apiEndpoints = {
  health: '/api/health/',
  auth: {
    login: '/auth/login/',
    register: '/auth/register/',
    changePassword: '/auth/change-password/',
    sendOtp: '/auth/send-otp/',
    verifyOtp: '/auth/verify-otp/',
    verifyPhone: '/auth/verify-phone/',
    forgotPassword: '/auth/forgot-password/',
    resetPassword: '/auth/reset-password/',
    googleConfig: '/auth/google/config/',
    googleStart: '/auth/google/start/',
    googleExchange: '/auth/google/exchange/',
    refresh: '/auth/refresh/',
    me: '/auth/me/',
    session: '/auth/session/',
  },
  companies: {
    profile: '/companies/profile/',
    registryLookup: '/companies/registry/lookup/',
    registryDraft: (draftId) => `/companies/registry/drafts/${draftId}/`,
    registryDraftConfirm: (draftId) => `/companies/registry/drafts/${draftId}/confirm/`,
    skipStir: '/companies/onboarding/skip-stir/',
  },
  tenders: {
    list: '/tenders/',
    manual: '/tenders/manual/',
    detail: (id) => `/tenders/${id}/`,
  },
  analysis: {
    start: '/analysis/start/',
    history: '/analysis/history/',
    status: (id) => `/analysis/${id}/status/`,
    result: (id) => `/analysis/${id}/result/`,
    calculate: (id) => `/analysis/${id}/calculate/`,
  },
  subscriptions: {
    plans: '/subscriptions/plans/',
    current: '/subscriptions/current/',
    status: '/subscriptions/status/',
    usage: '/subscriptions/usage/',
    entitlements: '/subscriptions/entitlements/',
    featureCheck: (feature) => `/subscriptions/features/${feature}/check/`,
    checkout: '/subscriptions/checkout/',
    clickPrepare: '/subscriptions/payments/click/prepare/',
    clickComplete: '/subscriptions/payments/click/complete/',
  },
  documents: {
    list: '/documents/',
    templates: '/documents/templates/',
    generate: '/documents/generate/',
    detail: (id) => `/documents/${id}/`,
    approve: (id) => `/documents/${id}/approve/`,
    archive: (id) => `/documents/${id}/archive/`,
    export: (id) => `/documents/${id}/export/`,
    versions: (id) => `/documents/${id}/versions/`,
    exportStatus: (id) => `/documents/exports/${id}/`,
  },
  teams: {
    workspace: '/teams/workspace/',
    members: '/teams/members/',
    member: (id) => `/teams/members/${id}/`,
    revokeSessions: (id) => `/teams/members/${id}/revoke-sessions/`,
  },
  competitors: {
    top: '/competitors/top/',
    freshness: '/competitors/freshness/',
    history: (stir) => `/competitors/${stir}/history/`,
  },
  admin: {
    stepUp: '/admin/auth/step-up/',
    overview: '/admin/overview/',
    search: '/admin/search/',
    users: '/admin/users/',
    user: (id) => `/admin/users/${id}/`,
    companies: '/admin/companies/',
    company: (id) => `/admin/companies/${id}/`,
    plans: '/admin/plans/',
    payments: '/admin/payments/',
    operations: '/admin/operations/',
    audit: '/admin/audit/',
    auditExport: '/admin/audit/export/',
  },
};

export function asApiV1Path(path) {
  return path.startsWith('/api/') ? path : `/api/v1${path}`;
}
