# Generated by Django 5.2.15 on 2026-06-14 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0002_tenderlot_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('lot', 'Lot'), ('category', 'Category')], max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('identity_key', models.CharField(max_length=550)),
                ('competitor_name', models.CharField(max_length=500)),
                ('competitor_stir', models.CharField(blank=True, default='', max_length=9)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('rank', models.PositiveIntegerField()),
                ('total_participations', models.PositiveIntegerField()),
                ('total_wins', models.PositiveIntegerField()),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_bid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('average_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('source_count', models.PositiveIntegerField()),
                ('raw_metrics', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField()),
                ('tender_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_analytics', to='tenders.tenderlot')),
            ],
            options={
                'db_table': 'competitor_analytics',
                'ordering': ['rank', 'identity_key'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorDataQualityIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], default='error', max_length=20)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('details', models.JSONField(default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_quality_issues', to='tenders.tenderlot')),
            ],
            options={
                'db_table': 'competitor_data_quality_issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=500)),
                ('normalized_name', models.CharField(max_length=500)),
                ('stir', models.CharField(blank=True, default='', max_length=9)),
                ('identity_key', models.CharField(max_length=550)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tenders.tenderlot')),
            ],
            options={
                'db_table': 'tender_participants',
                'ordering': ['tender_lot_id', 'normalized_name'],
            },
        ),
        migrations.CreateModel(
            name='TenderBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='competitors.tenderparticipant')),
            ],
            options={
                'db_table': 'tender_bids',
                'ordering': ['participant_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='TenderAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True, default='')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender_lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='tenders.tenderlot')),
                ('winning_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winning_awards', to='competitors.tenderbid')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='competitors.tenderparticipant')),
            ],
            options={
                'db_table': 'tender_awards',
            },
        ),
        migrations.CreateModel(
            name='CompetitorAnalyticsSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('was_winner', models.BooleanField(default=False)),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='competitors.competitoranalytics')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_sources', to='competitors.tenderaward')),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_sources', to='competitors.tenderbid')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_sources', to='competitors.tenderparticipant')),
            ],
            options={
                'db_table': 'competitor_analytics_sources',
            },
        ),
        migrations.AddIndex(
            model_name='competitoranalytics',
            index=models.Index(fields=['scope_type', 'tender_lot', 'rank'], name='competitor__scope_t_d9385d_idx'),
        ),
        migrations.AddIndex(
            model_name='competitoranalytics',
            index=models.Index(fields=['scope_type', 'category', 'rank'], name='competitor__scope_t_612d63_idx'),
        ),
        migrations.AddIndex(
            model_name='competitoranalytics',
            index=models.Index(fields=['competitor_stir', '-calculated_at'], name='competitor__competi_905dee_idx'),
        ),
        migrations.AddIndex(
            model_name='competitoranalytics',
            index=models.Index(fields=['-calculated_at'], name='competitor__calcula_5fd1c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitoranalytics',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'lot')), fields=('tender_lot', 'identity_key', 'period_start', 'period_end'), name='unique_lot_competitor_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='competitoranalytics',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'category')), fields=('category', 'identity_key', 'period_start', 'period_end'), name='unique_category_competitor_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='competitoranalytics',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='competitor_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='competitoranalytics',
            constraint=models.CheckConstraint(condition=models.Q(('total_wins__lte', models.F('total_participations'))), name='competitor_wins_not_above_participations'),
        ),
        migrations.AddConstraint(
            model_name='competitoranalytics',
            constraint=models.CheckConstraint(condition=models.Q(('win_rate__gte', 0), ('win_rate__lte', 100)), name='competitor_win_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='competitoranalytics',
            constraint=models.CheckConstraint(condition=models.Q(('average_discount_percentage__gte', 0), ('average_discount_percentage__lte', 100)), name='competitor_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='competitoranalytics',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_type', 'lot'), ('tender_lot__isnull', False)), models.Q(('category__gt', ''), ('scope_type', 'category'), ('tender_lot__isnull', True)), _connector='OR'), name='competitor_scope_fields_valid'),
        ),
        migrations.AddIndex(
            model_name='competitordataqualityissue',
            index=models.Index(fields=['code', 'resolved_at'], name='competitor__code_d7f406_idx'),
        ),
        migrations.AddIndex(
            model_name='competitordataqualityissue',
            index=models.Index(fields=['tender_lot', '-created_at'], name='competitor__tender__fd7ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderparticipant',
            index=models.Index(fields=['stir'], name='tender_part_stir_580af6_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderparticipant',
            index=models.Index(fields=['identity_key'], name='tender_part_identit_e18956_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenderparticipant',
            constraint=models.UniqueConstraint(fields=('tender_lot', 'identity_key'), name='unique_participant_identity_per_lot'),
        ),
        migrations.AddConstraint(
            model_name='tenderbid',
            constraint=models.UniqueConstraint(fields=('participant', 'sequence'), name='unique_bid_sequence_per_participant'),
        ),
        migrations.AddConstraint(
            model_name='tenderbid',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='tender_bid_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tenderbid',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='tender_bid_sequence_positive'),
        ),
        migrations.AddIndex(
            model_name='tenderaward',
            index=models.Index(fields=['is_verified', 'awarded_at'], name='tender_awar_is_veri_be51ca_idx'),
        ),
        migrations.AddIndex(
            model_name='competitoranalyticssource',
            index=models.Index(fields=['analytics', 'was_winner'], name='competitor__analyti_1f473f_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitoranalyticssource',
            constraint=models.UniqueConstraint(fields=('analytics', 'participant'), name='unique_analytics_participant_source'),
        ),
    ]
