# Generated by Django 5.2.15 on 2026-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
        ('tenders', '0004_tendersource_tenderlot_external_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='competitoranalytics',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gt', 0)), name='competitor_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='competitoranalytics',
            constraint=models.CheckConstraint(condition=models.Q(('source_count__gt', 0)), name='competitor_source_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='competitoranalytics',
            constraint=models.CheckConstraint(condition=models.Q(('average_bid_amount__gte', 0)), name='competitor_average_bid_non_negative'),
        ),
    ]
