# Generated by Django 5.2.15 on 2026-06-14 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('companies', '0003_alter_companyprofile_current_tariff'),
        ('tenders', '0002_tenderlot_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('application', 'Tender application'), ('guarantee', 'Guarantee letter'), ('commercial', 'Commercial proposal'), ('compliance', 'Technical compliance'), ('other', 'Other official letter')], max_length=30)),
                ('language', models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Русский')], max_length=10)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('draft', 'Draft'), ('approved', 'Approved'), ('exported', 'Exported'), ('failed', 'Failed'), ('archived', 'Archived')], default='generating', max_length=20)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('content_html', models.TextField(blank=True, default='')),
                ('content_text', models.TextField(blank=True, default='')),
                ('context_snapshot', models.JSONField(default=dict)),
                ('generation_metadata', models.JSONField(blank=True, default=dict)),
                ('template_version', models.PositiveIntegerField()),
                ('edit_version', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='analysis.aitenderanalysis')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='companies.companyprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_documents', to=settings.AUTH_USER_MODEL)),
                ('tender_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='tenders.tenderlot')),
            ],
            options={
                'db_table': 'generated_documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocumentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('content_json', models.JSONField(default=dict)),
                ('content_html', models.TextField()),
                ('content_text', models.TextField()),
                ('source', models.CharField(choices=[('generation', 'Generation'), ('edit', 'Edit'), ('approval', 'Approval')], max_length=20)),
                ('change_summary', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_revisions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.generateddocument')),
            ],
            options={
                'db_table': 'generated_document_revisions',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='DocumentExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/exports/%Y/%m/')),
                ('storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_exports', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='documents.generateddocument')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='documents.generateddocumentrevision')),
            ],
            options={
                'db_table': 'document_exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderDocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('application', 'Tender application'), ('guarantee', 'Guarantee letter'), ('commercial', 'Commercial proposal'), ('compliance', 'Technical compliance'), ('other', 'Other official letter')], max_length=30)),
                ('language', models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Русский')], max_length=10)),
                ('version', models.PositiveIntegerField()),
                ('prompt_template', models.TextField()),
                ('content_schema', models.JSONField(default=dict)),
                ('required_company_fields', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tender_document_templates',
                'ordering': ['document_type', 'language', '-version'],
            },
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='documents.tenderdocumenttemplate'),
        ),
        migrations.CreateModel(
            name='DocumentAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('generation_requested', 'Generation requested'), ('generation_completed', 'Generation completed'), ('generation_failed', 'Generation failed'), ('edited', 'Edited'), ('approved', 'Approved'), ('export_requested', 'Export requested'), ('export_completed', 'Export completed'), ('export_failed', 'Export failed'), ('archived', 'Archived')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_audit_events', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='documents.generateddocument')),
            ],
            options={
                'db_table': 'document_audit_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='document_au_documen_a4be42_idx'), models.Index(fields=['event', '-created_at'], name='document_au_event_7a0de8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='generateddocumentrevision',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='unique_document_revision_version'),
        ),
        migrations.AddConstraint(
            model_name='generateddocumentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='document_revision_version_positive'),
        ),
        migrations.AddIndex(
            model_name='documentexport',
            index=models.Index(fields=['document', 'status', '-created_at'], name='document_ex_documen_193d04_idx'),
        ),
        migrations.AddIndex(
            model_name='documentexport',
            index=models.Index(fields=['requested_by', '-created_at'], name='document_ex_request_938604_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderdocumenttemplate',
            index=models.Index(fields=['document_type', 'language', 'is_active'], name='tender_docu_documen_be314d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderdocumenttemplate',
            index=models.Index(fields=['code', 'is_active'], name='tender_docu_code_632505_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenderdocumenttemplate',
            constraint=models.UniqueConstraint(fields=('code', 'language', 'version'), name='unique_document_template_version'),
        ),
        migrations.AddConstraint(
            model_name='tenderdocumenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('code', 'language'), name='one_active_document_template'),
        ),
        migrations.AddConstraint(
            model_name='tenderdocumenttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='document_template_version_positive'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['company', 'status', '-updated_at'], name='generated_d_company_fb9a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['tender_lot', 'document_type'], name='generated_d_tender__3b2088_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['created_by', '-created_at'], name='generated_d_created_704bf5_idx'),
        ),
    ]
