# Generated by Django 5.2.15 on 2026-06-14 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_aitenderanalysis_analysis_eligibility_score_range_and_more'),
        ('companies', '0004_companyprofile_company_stir_format_and_more'),
        ('documents', '0002_seed_initial_templates'),
        ('tenders', '0004_tendersource_tenderlot_external_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentexport',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__isnull', True), ('file_size__gte', 0), _connector='OR'), name='document_export_file_size_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='generateddocument',
            constraint=models.CheckConstraint(condition=models.Q(('template_version__gt', 0)), name='generated_document_template_version_positive'),
        ),
    ]
