# Generated by Django 5.2.14 on 2026-05-22 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stir', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('company_name', models.CharField(max_length=500)),
                ('company_type', models.CharField(choices=[('yatt', 'YaTT'), ('mchj', 'MChJ'), ('aj', 'AJ'), ('tt', 'TT')], default='mchj', max_length=20)),
                ('industry', models.CharField(max_length=255)),
                ('experience_level', models.CharField(choices=[('beginner', 'Yangi boshlovchi'), ('intermediate', "O'rtacha"), ('expert', 'Professional')], default='beginner', max_length=20)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('ustav_fondi', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('has_vat', models.BooleanField(default=False)),
                ('current_tariff', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('tariff_expires_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_answers', models.JSONField(blank=True, default=dict)),
                ('raw_tax_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'current_tariff'], name='company_pro_user_id_51e6cb_idx'), models.Index(fields=['industry'], name='company_pro_industr_dbd29a_idx')],
            },
        ),
    ]
