# Generated by Django 5.2.15 on 2026-06-14 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def mark_existing_stir_profiles_as_manual(apps, schema_editor):
    CompanyProfile = apps.get_model('companies', 'CompanyProfile')
    CompanyProfile.objects.filter(stir__isnull=False).exclude(stir='').update(
        registry_source='manual',
        registry_status='manual',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistryDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stir', models.CharField(max_length=9)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('confirmed_data', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('manual', "Qo'lda kiritilgan"), ('tax', 'Soliq reyestri'), ('statistics', 'Statistika reyestri')], default='manual', max_length=20)),
                ('lookup_metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('ready', 'Tasdiqlashga tayyor'), ('confirmed', 'Tasdiqlangan'), ('expired', 'Muddati tugagan'), ('failed', 'Xatolik')], default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=50)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('cache_hit', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_registry_drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='director_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='legal_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='registry_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='registry_source',
            field=models.CharField(choices=[('manual', "Qo'lda kiritilgan"), ('tax', 'Soliq reyestri'), ('statistics', 'Statistika reyestri')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='registry_status',
            field=models.CharField(choices=[('not_checked', 'Tekshirilmagan'), ('pending', 'Tekshirilmoqda'), ('verified', 'Tasdiqlangan'), ('not_found', 'Topilmadi'), ('failed', 'Tekshiruv xatosi'), ('manual', "Qo'lda kiritilgan")], default='not_checked', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='stir_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_stir_profiles_as_manual,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['registry_status', 'registry_source'], name='company_pro_registr_4a522f_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyprofile',
            constraint=models.CheckConstraint(condition=models.Q(('stir__isnull', True), ('stir_skipped', False), _connector='OR'), name='company_stir_not_skipped'),
        ),
        migrations.AddField(
            model_name='companyregistrydraft',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_drafts', to='companies.companyprofile'),
        ),
        migrations.AddField(
            model_name='companyregistrydraft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_registry_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='companyregistrydraft',
            index=models.Index(fields=['user', 'status'], name='company_reg_user_id_00effa_idx'),
        ),
        migrations.AddIndex(
            model_name='companyregistrydraft',
            index=models.Index(fields=['provider', 'stir'], name='company_reg_provide_ca5269_idx'),
        ),
        migrations.AddIndex(
            model_name='companyregistrydraft',
            index=models.Index(fields=['expires_at'], name='company_reg_expires_8e8ca0_idx'),
        ),
    ]
