# Generated by Django 5.2.15 on 2026-06-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyregistrydraft_companyprofile_director_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='current_tariff',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
