# Generated by Django 5.2.15 on 2026-06-14 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companyprofile_current_tariff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companyprofile',
            constraint=models.CheckConstraint(condition=models.Q(('stir__isnull', True), ('stir__regex', '^[0-9]{9}$'), _connector='OR'), name='company_stir_format'),
        ),
        migrations.AddConstraint(
            model_name='companyregistrydraft',
            constraint=models.CheckConstraint(condition=models.Q(('stir__regex', '^[0-9]{9}$')), name='registry_draft_stir_format'),
        ),
    ]
