# Generated by Django 5.2.15 on 2026-06-14 18:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


OWNER_PERMISSIONS = [
    'view_lots',
    'export_lot_data',
    'run_ai_analysis',
    'use_analysis_quotas',
    'generate_ai_contracts',
    'edit_inline_workspace',
    'export_pdf_docx',
    'access_competitor_metrics',
    'manage_team',
]


def backfill_company_owners(apps, schema_editor):
    CompanyProfile = apps.get_model('companies', 'CompanyProfile')
    CompanyMember = apps.get_model('teams', 'CompanyMember')
    CompanyMember.objects.bulk_create([
        CompanyMember(
            company_id=company.id,
            user_id=company.user_id,
            role='owner',
            permissions=OWNER_PERMISSIONS,
            force_password_change=False,
            is_active=True,
        )
        for company in CompanyProfile.objects.all().iterator()
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_companyprofile_company_stir_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('viewer', 'Viewer')], max_length=20)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('force_password_change', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.companyprofile')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_members',
                'ordering': ['role', 'user__full_name'],
                'indexes': [models.Index(fields=['company', 'is_active', 'role'], name='company_mem_company_cfcac3_idx'), models.Index(fields=['user', 'is_active'], name='company_mem_user_id_61fbd3_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'user'), name='unique_company_member')],
            },
        ),
        migrations.CreateModel(
            name='TeamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_jti', models.CharField(max_length=255, unique=True)),
                ('device', models.CharField(blank=True, default='', max_length=255)),
                ('browser', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_sessions',
                'ordering': ['-last_active_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at', 'last_active_at'], name='team_sessio_user_id_5a859d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('token_jti__gt', '')), name='team_session_jti_not_empty')],
            },
        ),
        migrations.RunPython(
            backfill_company_owners,
            migrations.RunPython.noop,
        ),
    ]
