# Generated by Django 5.2.15 on 2026-06-15 03:31

from django.db import migrations, models


def backfill_visual_permissions(apps, schema_editor):
    CompanyMember = apps.get_model('teams', 'CompanyMember')
    for member in CompanyMember.objects.all().iterator():
        permissions = set(member.permissions or [])
        member.can_search_lots = 'view_lots' in permissions
        member.can_run_ai_analysis = 'run_ai_analysis' in permissions
        member.can_generate_documents = 'generate_ai_contracts' in permissions
        member.can_view_competitor_metrics = (
            'access_competitor_metrics' in permissions
        )
        member.save(update_fields=[
            'can_search_lots',
            'can_run_ai_analysis',
            'can_generate_documents',
            'can_view_competitor_metrics',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymember',
            name='can_generate_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companymember',
            name='can_run_ai_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companymember',
            name='can_search_lots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companymember',
            name='can_view_competitor_metrics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamsession',
            name='audience',
            field=models.CharField(default='web', max_length=50),
        ),
        migrations.AddField(
            model_name='teamsession',
            name='auth_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsession',
            name='mfa_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsession',
            name='revoked_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teamsession',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='companymember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], max_length=20),
        ),
        migrations.RunPython(
            backfill_visual_permissions,
            migrations.RunPython.noop,
        ),
    ]
