# Generated by Django 5.2.15 on 2026-06-14 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPrincipal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('mfa_verified_at', models.DateTimeField(blank=True, null=True)),
                ('step_up_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_admin_principals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_principal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_principals',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('document_generation', 'document_generation'), ('document_export', 'document_export'), ('competitor_intelligence', 'competitor_intelligence'), ('team_collaboration', 'team_collaboration'), ('advanced_audit', 'advanced_audit')], max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_feature_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_feature_flags',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('maintenance_banner', 'Maintenance banner')], max_length=100, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_system_settings',
            },
        ),
        migrations.CreateModel(
            name='AdminActionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('response_status', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_action_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_action_requests',
                'indexes': [models.Index(fields=['actor', '-created_at'], name='admin_actio_actor_i_0bd8ed_idx'), models.Index(fields=['action', 'status'], name='admin_actio_action_8b8f39_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor', 'idempotency_key'), name='unique_admin_idempotency_key')],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.TextField()),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=20)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_audit_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='admin_audit_actor_i_028421_idx'), models.Index(fields=['action', '-created_at'], name='admin_audit_action_6b1f11_idx'), models.Index(fields=['target_type', 'target_id'], name='admin_audit_target__2e31fe_idx')],
            },
        ),
    ]
