# Generated by Django 5.2.15 on 2026-06-15 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlplane', '0003_seed_system_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvariantDiagnosticCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=150, unique=True)),
                ('value', models.BigIntegerField(default=0)),
                ('source_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unavailable', 'Unavailable'), ('stale', 'Stale')], default='healthy', max_length=20)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('diagnostic_message', models.TextField(blank=True, default='')),
                ('observed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_invariant_counters',
                'indexes': [models.Index(fields=['source_status', '-observed_at'], name='admin_invar_source__d48674_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='admin_invariant_counter_non_negative')],
            },
        ),
    ]
