# Generated by Django 5.2.14 on 2026-05-21 21:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text="O'zbekiston formati: +998901234567", max_length=15, null=True, unique=True, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name="To'liq ism")),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('user', 'Foydalanuvchi'), ('manager', 'Menejer'), ('viewer', 'Kuzatuvchi')], default='user', max_length=20, verbose_name='Rol')),
                ('auth_provider', models.CharField(choices=[('phone', 'Telefon + OTP'), ('google', 'Google OAuth')], default='phone', max_length=20, verbose_name='Auth usuli')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
    ]
