# Generated by Django 5.2.14 on 2026-05-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(choices=[('phone', 'Telefon + OTP'), ('google', 'Google OAuth'), ('email', 'Email + Parol')], default='phone', max_length=20, verbose_name='Auth usuli'),
        ),
    ]
