# Generated by Django 5.2.15 on 2026-06-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
