# Generated by Django 5.2.15 on 2026-06-14 17:40

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_customuser_auth_version'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('phone_number__isnull', False), models.Q(('phone_number', ''), _negated=True)), models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), _connector='OR'), name='user_has_login_identity'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), name='unique_user_email_ci'),
        ),
    ]
