# Generated by Django 5.2.15 on 2026-06-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_user_has_login_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_mfa_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mfa_method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mfa_recovery_codes_hash',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mfa_secret_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
